### ISSUE TITLE
Putting an empty food pouch in an icebox causes a division by zero

### ISSUE THREAD

**Issue by sentwayfarer** [Viola-Siemens/Freeze-It-And-Heat-It#1]
I tried to put an empty food pouch in an icebox and it caused a crash. Possible reason is that there may be no check if there is nothing in the pouch.
[crash-2023-09-14_20.42.38-server.txt](https://github.com/Viola-Siemens/Freeze-It-And-Heat-It/files/12614803/crash-2023-09-14_20.42.38-server.txt)
[latest.log](https://github.com/Viola-Siemens/Freeze-It-And-Heat-It/files/12614806/latest.log)

**Comment by Viola-Siemens** [comment]
Thanks for contribution. Bug is fixed and new file is availabled to download.
https://legacy.curseforge.com/minecraft/mc-mods/freeze-it-and-heat-it/files/4752911
https://modrinth.com/mod/freeze-it-and-heat-it/version/1.2.1
