### ISSUE TITLE
[1.19.2] Crash on ticking entities

### ISSUE THREAD

**Issue by 1ezekiil** [Viola-Siemens/Freeze-It-And-Heat-It#12]
Hello!

I have the latest version of the mod on 1.19.2 - 2.2.4
When i was flying around the world, minecraft completely crashes.
In crash report FrozenRottenFood have no TEMP_Rate field.

Here is crash report (i don't know, if this can be reproducible, because of 100+ mods, but anyway)
https://pastebin.com/kc9yCSSn

**Comment by Viola-Siemens** [comment]
Duplicated #11
