### ISSUE TITLE
整合包加入后无限加载

### ISSUE THREAD

**Issue by uzu11** [Viola-Siemens/Freeze-It-And-Heat-It#13]
[minecraft-exported-logs-2024-05-27T10-25-33.log](https://github.com/Viola-Siemens/Freeze-It-And-Heat-It/files/15450162/minecraft-exported-logs-2024-05-27T10-25-33.log)

**Comment by Viola-Siemens** [comment]
Further information needed. Are you using Cold Sweat 2.2.5.1? If not, try CS 2.2.5.1 instead of beta versions. We can only make sure that FIAHI supports the latest release of CS.
需要一些更多信息，你是否在使用冷汗2.2.5.1？如果不是，将冷汗版本降到2.2.5.1，不要使用beta版，因为我们仅仅保证FIAHI支持冷汗最新的正式版。
