### ISSUE TITLE
Crash on startup (1.20.1 forge)

### ISSUE THREAD

**Issue by NotTohm** [Viola-Siemens/Freeze-It-And-Heat-It#14]
https://paste.ee/p/A0Agh

**Comment by Viola-Siemens** [comment]
duplicated #11 
please use Cold Sweat v2.2.5.1

**Comment by NotTohm** [comment]
is it gonna get updated to the latest version anytime soon?

**Comment by Viola-Siemens** [comment]
> is it gonna get updated to the latest version anytime soon?

The latest version is always matching the latest release of Cold Sweat. However, you are using a beta CS.

**Comment by NotTohm** [comment]
oh ok, thanks
