### ISSUE TITLE
Mod crashes upon loading / 1.20.1 Forge ( All versions of 1.20.1 Forge ) /

### ISSUE THREAD

**Issue by atomicparticle** [Viola-Siemens/Freeze-It-And-Heat-It#19]
Hello dear developer(s),

Love the mod, I really want to try playing with it in 1.20.1 in my new modpack. 

Sadly, when I attempt to load in via CurseForge launcher or just simple Minecraft Forge, the game crashes and does not provide a crash report, only an exit code; "Exit Code 1". I tried to dig through my logs, but I was unable to locate a complete crash report related to this instance.

I tried changing Forge versions within 1.20.1 Forge, but all ( 47.0.0 to 47.3.6 ) crashed and did not give me a crash report, only the exit code error I described above.

Just to make sure I didn't use the wrong version, I used a file named "fiahi-3.1.0.jar" for the manual install that I downloaded from Modrinth ( I also tried the CurseForge file. ), which said 1.20.1 as a version, and I tried the CurseForge client that said the name of the file was the same, I even checked the file manually in the folder and the name matched. I tried running the mod with only the required "Cold Sweat" version and "Freeze It, and Heat it!" installed because I feared my other mods were conflicting, but the error persisted. 

I saw some other users in the Curseforge page comment section claiming to have the same issue I have.

My PC has the Java version up to date for Minecraft ( Forge 1.20.1 - 47.3.0 and below ) and haven't had issues before, I gave the game 6 gigabytes of RAM, and thankfully my PC is in good condition so performance issues can be maybe ruled out.

Again, love the mod and keep up the good work, it made our friend circle servers much more fun!

Thank you and have a great day,
 - atomicparticle

**Comment by Viola-Siemens** [comment]
which version of Cold Sweat are you using? 3.1.0 only supports from 2.2.3 to 2.2.5.1, while 3.1.1 which I'm working on will supports 2.3 and upper.

**Comment by Viola-Siemens** [comment]
If you are using correct version of CS, please upload your latest.log and crash report, and I'll try to fix it.

**Comment by atomicparticle** [comment]
I was using the 2.3 version of Cold Sweat with 3.1.0, now I understand, I was not aware of this. Thank you for responding, how much time do you estimate 3.1.1 will be out in? No rush of course, just eager to play the mod!

**Comment by Viola-Siemens** [comment]
Thanks for your supporting.
