### ISSUE TITLE
Possible memory leak caused my method used in your mod

### ISSUE THREAD

**Issue by Maypul** [Viola-Siemens/Freeze-It-And-Heat-It#5]
Copied over from: https://github.com/Momo-Softworks/Cold-Sweat/issues/201

MC: 1.19.2 / Forge: 43.2.21
Mod list (client): https://pastebin.com/Js1fz01f

Snip from the error:
[08:41:26] [Server thread/FATAL] [ModernFix/]: A mod is accessing chunks from a stopped server (this will also cause memory leaks)
java.lang.Exception
at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerChunkCache.handler$zec000$bailIfServerDead(ServerChunkCache.java:1596)
~ cut for char limit~
at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.biome.BiomeManager.m_204214_(BiomeManager.java:79)
at TRANSFORMER/cold_sweat@2.2.2/com.momosoftworks.coldsweat.api.temperature.modifier.BiomeTempModifier.calculate(BiomeTempModifier.java:52)
at TRANSFORMER/cold_sweat@2.2.2/com.momosoftworks.coldsweat.api.temperature.modifier.TempModifier.update(TempModifier.java:60)
at TRANSFORMER/cold_sweat@2.2.2/com.momosoftworks.coldsweat.api.util.Temperature.apply(Temperature.java:114)
at TRANSFORMER/cold_sweat@2.2.2/com.momosoftworks.coldsweat.api.util.Temperature.apply(Temperature.java:130)
at TRANSFORMER/cold_sweat@2.2.2/com.momosoftworks.coldsweat.api.util.Temperature.getTemperatureAt(Temperature.java:138)
at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.item.ItemEntity.mdb608ee$lambda$tickFood$0$0(ItemEntity.java:1034)
at TRANSFORMER/forge@43.2.21/net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:150)
at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.item.ItemEntity.handler$bfl000$tickFood(ItemEntity.java:1033)
at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.item.ItemEntity.m_8119_(ItemEntity.java:98)
at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerLevel.track(ServerLevel.java:6240)
at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerLevel.redirect$dko000$onTickNonPassenger(ServerLevel.java:6256)
~ cut for message limit~
at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244)
at java.base/java.lang.Thread.run(Thread.java:833)

The issue: it seems that with combination of mods there is some memory leaking, in the error catched by ModernFix it seems like it could be Cold Sweat issue (it mentions the mod) - apparently method your mod uses in this case.
How to reproduce: Have the mod list, enter the world, do something, leave the world, enter the world again, do something, and there is a chance these error happen.
I managed to remove the error if I remove from the pack: Thermal Expansion or Freeze It, and Heat It! (addon to Cold Sweat) but these mods does not seem like the core issue - I am having an issue with finding core issue ,as running an instance with only Thermal mods, Modern Fix and Cold Sweat + addon the error does not happen, but the error itself mentions Coldsweat. Observable was removed and the issue still happened.

Full example latest.log: https://easyupload.io/mikitm and [newlog.txt](https://github.com/Momo-Softworks/Cold-Sweat/files/13634886/newlog.txt) (with -Dmodernfix.debugBadChunkloading=true flag to log more error message)

**Comment by MikulDev** [comment]
To give some more information, the method in question is the `Temperature.getTemperatureAt()` method used in a `TickEvent` subscriber. Likely to tick food spoilage. In this case, it would probably be better to use `Temperature.get(player, Temperature.Types.WORLD)`, since the player is provided in the event. Plus, it's more accurate than `getTemperatureAt()`.

**Comment by Viola-Siemens** [comment]
> To give some more information, the method in question is the `Temperature.getTemperatureAt()` method used in a `TickEvent` subscriber. Likely to tick food spoilage. In this case, it would probably be better to use `Temperature.get(player, Temperature.Types.WORLD)`, since the player is provided in the event. Plus, it's more accurate than `getTemperatureAt()`.

But how can I get temperature at a block position since I need to tick food in containers or itementity spoilage if I'm not supposed to use `getTemperatureAt`? WorldTickEvent does not provide any player.

**Comment by Viola-Siemens** [comment]
So here's what I guess. ModernFix makes some chunks unloaded to save memory, and I'm trying to get temperature at a block position by `getTemperatureAt` given by Cold Sweat, which creates a dummy silverfish but not adds it to the current level, and tries to get it world temperature from biome temperature modifier. But the chunk is unloaded so ModernFix forbid me to get the biome temperature modifier? But why item entity and block entity is still updating in unloaded chunk? I'm confused.

**Comment by MikulDev** [comment]
That's a very good question. I'd say it's because the check is happening _right next to_ an unloaded chunk, and biome temperature checks nearby chunks to get the average. Although that raises the question of why the player is next to an unloaded chunk.

 The only other thing I can think of is that the player is loaded before the world, which could also cause this issue. In single player, if you leave a world, the player still exists and the integrated server continues running. This would mean that if you join a new world, the player object already exists before the world loads, so the check happens too early and ModernFix flags it as an unloaded chunk.

These are just guesses based on my troubleshooting in the past.

**Comment by MikulDev** [comment]
> > To give some more information, the method in question is the `Temperature.getTemperatureAt()` method used in a `TickEvent` subscriber. Likely to tick food spoilage. In this case, it would probably be better to use `Temperature.get(player, Temperature.Types.WORLD)`, since the player is provided in the event. Plus, it's more accurate than `getTemperatureAt()`.
> 
> But how can I get temperature at a block position since I need to tick food in containers or itementity spoilage if I'm not supposed to use `getTemperatureAt`? WorldTickEvent does not provide any player.

In this case you have no choice but to use getTemperatureAt. I didn't say not to use it in general, just that it isn't necessary when the player is already provided to you.

**Comment by Viola-Siemens** [comment]
> That's a very good question. I'd say it's because the check is happening _right next to_ an unloaded chunk, and biome temperature checks nearby chunks to get the average. Although that raises the question of why the player is next to an unloaded chunk.
> 
> The only other thing I can think of is that the player is loaded before the world, which could also cause this issue. In single player, if you leave a world, the player still exists and the integrated server continues running. This would mean that if you join a new world, the player object already exists before the world loads, so the check happens too early and ModernFix flags it as an unloaded chunk.
> 
> These are just guesses based on my troubleshooting in the past.

Thanks for this. I checked the log again and find that the client player does leave a world and join a new one. I think maybe you can add
```
if (!dummy.level.equals(level)) {
    dummy = new Silverfish(EntityType.SILVERFISH, level);
    DUMMIES.replace(level.dimension().location(), dummy);
}
```
before [here](https://github.com/Momo-Softworks/Cold-Sweat/blob/1.19.2-FG/src/main/java/com/momosoftworks/coldsweat/api/util/Temperature.java#L137) to fix it?
