### ISSUE TITLE
[建议] 调整食物温度tooltip

### ISSUE THREAD

**Issue by wumengzhixing** [Viola-Siemens/Freeze-It-And-Heat-It#8]
部分食物在配置中已经被取消了温度的设定，但是还是会显示出新鲜食物的tooltip，导致玩家会认为这些食物也会同样受温度影响，因此希望能做个调整
![image](https://github.com/Viola-Siemens/Freeze-It-And-Heat-It/assets/88496786/1e639983-d1f9-4154-b405-901c441749f8)

**Comment by Viola-Siemens** [comment]
Fix in 59c9762
