### ISSUE TITLE
Crash when trying to add cold "fuel" items to icebox 

### ISSUE THREAD

**Issue by kostikyanni** [Viola-Siemens/Freeze-It-And-Heat-It#9]
Minecraft version: 1.19.2
Forge version: 43.3.7
ColdSweat version 2.3-b01a 
Freeze It, and Heat It! version 2.2.3

Steps to reproduce:

1. Create new singleplayer world with creative mode, hard difficulty, default biome settings
2. Place icebox on dirt
3. Right click icebox with cold fuel item like snowballs or ice in hand OR try to feed the cold fuel items in with hopper OR empty hand right click on icebox first and then try to manually place cold fuel items in the GUI fuel slot of icebox 
4. Game crashes 

[crash-2024-02-13_11.05.35-client.txt](https://github.com/Viola-Siemens/Freeze-It-And-Heat-It/files/14269903/crash-2024-02-13_11.05.35-client.txt)

**Comment by Viola-Siemens** [comment]
Cannot reproduce in release versions. You can probably install ColdSweat v2.2.5 instead of v2.3-b to fix it. If API changes in future release versions of CS, I'll publish a new release.
